<?php

declare(strict_types=1);

namespace Angeo\RobotsTxtAeo\Model\Sitemap;

use Angeo\RobotsTxtAeo\Model\UrlFetcher;
use Magento\Framework\App\ResourceConnection;
use Psr\Log\LoggerInterface;

/**
 * Reads sitemap entries generated by Magento_Sitemap.
 *
 * Magento_Sitemap is a soft dependency: the module works without it, and we do
 * not want a hard composer requirement just to read two columns. Until 4.0.0
 * that was solved with ObjectManagerInterface as a service locator, which the
 * Magento coding standard rejects (and Marketplace review flags).
 *
 * The table is read directly instead. It is a stable, documented schema, the
 * query is two columns with a store filter, and when the table is absent the
 * provider simply returns nothing.
 *
 * @since 4.0.0 — direct ObjectManager use removed.
 */
class MagentoSitemapProvider implements MagentoSitemapProviderInterface
{
    private const TABLE = 'sitemap';

    public function __construct(
        private readonly ResourceConnection $resourceConnection,
        private readonly UrlFetcher         $urlFetcher,
        private readonly LoggerInterface    $logger,
    ) {}

    /**
     * @return string[]
     */
    public function getSitemapUrls(?int $storeId = null): array
    {
        try {
            $connection = $this->resourceConnection->getConnection();
            $table      = $this->resourceConnection->getTableName(self::TABLE);

            if (!$connection->isTableExists($table)) {
                return []; // Magento_Sitemap not installed
            }

            $select = $connection->select()
                ->from($table, ['sitemap_path', 'sitemap_filename']);

            if ($storeId !== null) {
                $select->where('store_id = ?', $storeId);
            }

            $base = $this->urlFetcher->getBaseUrl($storeId);
            $urls = [];

            foreach ($connection->fetchAll($select) as $row) {
                $filename = trim((string) ($row['sitemap_filename'] ?? ''));
                if ($filename === '') {
                    continue;
                }

                $path     = trim((string) ($row['sitemap_path'] ?? ''), '/');
                $relative = ($path === '' ? '' : '/' . $path) . '/' . ltrim($filename, '/');
                $urls[]   = $base . $relative;
            }

            return array_values(array_unique($urls));
        } catch (\Throwable $e) {
            $this->logger->warning('[Angeo_RobotsTxtAeo] Magento_Sitemap lookup failed: ' . $e->getMessage());
            return [];
        }
    }
}
